# Generated by Django 3.2.5 on 2021-08-05 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='username')),
                ('image', models.ImageField(blank=True, upload_to='teacher_img/', verbose_name="O'qituvchi rasmi")),
                ('tel_num', models.CharField(blank=True, max_length=50, verbose_name='Telefon raqami')),
                ('subject', models.CharField(max_length=250, verbose_name="Qaysi fandan dars o'tishi")),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Bitta dars uchun narx')),
                ('countsub', models.PositiveIntegerField(default=0, verbose_name='Bir oydagi darslar soni')),
                ('allprice', models.PositiveIntegerField(verbose_name='Jami maosh')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Ismi')),
                ('surname', models.CharField(max_length=150, verbose_name='Familiyasi')),
                ('slug', models.SlugField(unique=True, verbose_name='username')),
                ('image', models.ImageField(blank=True, upload_to=None, verbose_name="O'quvchi rasmi")),
                ('tel_num', models.CharField(blank=True, max_length=50, verbose_name='Telefon raqami')),
                ('place', models.CharField(max_length=50, verbose_name='Yashash manzili')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Bitta dars uchun narx')),
                ('countsub', models.PositiveIntegerField(default=0, verbose_name='Bir oydagi darslar soni')),
                ('payed', models.BooleanField(default=False, verbose_name="to'lov qildi/qimadi")),
                ('allprice', models.PositiveIntegerField(verbose_name="Jami to'lov")),
                ('came', models.BooleanField(default=False, verbose_name='keldi/kemadi')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student', to='main.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('came_time', models.DateTimeField(verbose_name='Kelgan sanasi')),
                ('pay_time', models.DateTimeField(verbose_name="To'lov qilgan sanasi")),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='main.student')),
            ],
        ),
    ]
