# Generated by Django 3.2.4 on 2021-08-09 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210805_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='allprice',
            field=models.PositiveIntegerField(default=0, verbose_name="Jami to'lov"),
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, upload_to='student_img/', verbose_name="O'quvchi rasmi"),
        ),
    ]
