# Generated by Django 3.2.5 on 2021-08-08 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210805_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='payed',
            field=models.BooleanField(default=False, verbose_name="keldi/to'ladi"),
        ),
        migrations.AlterField(
            model_name='history',
            name='came_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Kelgan sanasi'),
        ),
        migrations.AlterField(
            model_name='history',
            name='pay_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name="To'lov qilgan sanasi"),
        ),
        migrations.AlterField(
            model_name='student',
            name='allprice',
            field=models.PositiveIntegerField(default=0, verbose_name="Jami to'lov"),
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, upload_to='student_img/', verbose_name="O'quvchi rasmi"),
        ),
    ]
