# Generated by Django 3.2.4 on 2021-08-08 13:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210805_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='came_time',
        ),
        migrations.RemoveField(
            model_name='history',
            name='pay_time',
        ),
        migrations.AddField(
            model_name='history',
            name='payed',
            field=models.BooleanField(default=False, verbose_name="keldi/to'ladi"),
        ),
        migrations.AddField(
            model_name='history',
            name='payed_money',
            field=models.PositiveIntegerField(default=0, verbose_name="To'lagan summasi"),
        ),
        migrations.AddField(
            model_name='history',
            name='time',
            field=models.CharField(blank=True, max_length=100, verbose_name='Kelgan sanasi'),
        ),
        migrations.AddField(
            model_name='student',
            name='date',
            field=models.DateField(auto_now=True, verbose_name="Qo'shilgan sanai"),
        ),
        migrations.AddField(
            model_name='teacher',
            name='address',
            field=models.CharField(default=datetime.datetime(2021, 8, 8, 13, 30, 48, 189541, tzinfo=utc), max_length=100, verbose_name='Yashash manzili'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='age',
            field=models.PositiveIntegerField(default=20, verbose_name='Yoshi'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='date',
            field=models.DateField(auto_now=True, verbose_name="Qo'shilgan sanai"),
        ),
        migrations.AddField(
            model_name='teacher',
            name='province',
            field=models.CharField(default=datetime.datetime(2021, 8, 8, 13, 31, 1, 141386, tzinfo=utc), max_length=50, verbose_name='Viloyat nomi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='sur_name',
            field=models.CharField(default=datetime.datetime(2021, 8, 8, 13, 31, 13, 589033, tzinfo=utc), max_length=100, verbose_name='Familiyasi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='allprice',
            field=models.PositiveIntegerField(default=0, verbose_name="Jami to'lov"),
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, upload_to='student_img/', verbose_name="O'quvchi rasmi"),
        ),
    ]
