# Generated by Django 3.2.5 on 2021-08-08 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210808_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='payed_money',
            field=models.PositiveIntegerField(default=0, verbose_name="To'lagan summasi"),
        ),
    ]
