# Generated by Django 3.2.5 on 2021-08-08 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_history_payed_money'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='came_time',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='history',
            name='pay_time',
        ),
    ]
