# Generated by Django 3.2.5 on 2021-08-08 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210808_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='time',
            field=models.CharField(blank=True, max_length=100, verbose_name='Kelgan sanasi'),
        ),
    ]
